# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('Round Robin', 'Round Robin'), ('1st Round', '1st Round'), ('2nd Round', '2nd Round'), ('3rd Round', '3rd Round'), ('4th Round', '4th Round'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('The Final', 'The Final')], max_length=20)),
                ('date', models.DateField()),
                ('winner', models.CharField(max_length=50)),
                ('loser', models.CharField(max_length=50)),
                ('winner_rank', models.PositiveIntegerField(null=True)),
                ('loser_rank', models.PositiveIntegerField(null=True)),
                ('winner_points', models.PositiveIntegerField(null=True)),
                ('loser_points', models.PositiveIntegerField(null=True)),
                ('w1', models.PositiveIntegerField(null=True)),
                ('w2', models.PositiveIntegerField(null=True)),
                ('w3', models.PositiveIntegerField(null=True)),
                ('w4', models.PositiveIntegerField(null=True)),
                ('w5', models.PositiveIntegerField(null=True)),
                ('l1', models.PositiveIntegerField(null=True)),
                ('l2', models.PositiveIntegerField(null=True)),
                ('l3', models.PositiveIntegerField(null=True)),
                ('l4', models.PositiveIntegerField(null=True)),
                ('l5', models.PositiveIntegerField(null=True)),
                ('comment', models.CharField(choices=[('Completed', 'Completed'), ('Retired', 'Retired'), ('Walkover', 'Walkover')], max_length=20)),
                ('B365W', models.FloatField(null=True)),
                ('B365L', models.FloatField(null=True)),
                ('BWW', models.FloatField(null=True)),
                ('BWL', models.FloatField(null=True)),
                ('CBW', models.FloatField(null=True)),
                ('CBL', models.FloatField(null=True)),
                ('EXW', models.FloatField(null=True)),
                ('EXL', models.FloatField(null=True)),
                ('LBW', models.FloatField(null=True)),
                ('LBL', models.FloatField(null=True)),
                ('GBW', models.FloatField(null=True)),
                ('GBL', models.FloatField(null=True)),
                ('IWW', models.FloatField(null=True)),
                ('IWL', models.FloatField(null=True)),
                ('PSW', models.FloatField(null=True)),
                ('PSL', models.FloatField(null=True)),
                ('SBW', models.FloatField(null=True)),
                ('SBL', models.FloatField(null=True)),
                ('SJW', models.FloatField(null=True)),
                ('SJL', models.FloatField(null=True)),
                ('UBW', models.FloatField(null=True)),
                ('UBL', models.FloatField(null=True)),
                ('MaxW', models.FloatField(null=True)),
                ('MaxL', models.FloatField(null=True)),
                ('AvgW', models.FloatField(null=True)),
                ('AvgL', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(choices=[('ATP250', 'ATP250'), ('ATP500', 'ATP500'), ('Grand Slam', 'Grand Slam'), ('Masters 1000', 'Masters 1000'), ('Masters Cup', 'Masters Cup')], default='ATP250', max_length=20)),
                ('court', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor')], max_length=20)),
                ('surface', models.CharField(choices=[('Carpet', 'Carpet'), ('Clay', 'Clay'), ('Grass', 'Grass'), ('Hard', 'Hard')], max_length=20)),
                ('men_max_nb_set', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tennis.Tournament'),
        ),
    ]
